name: Build transmission-daemon Base Workflow

on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string

jobs:
  build-transmission-daemon:
    runs-on: ubuntu-latest
    env:
      working-directory: ./transmission-daemon
      TRANSMISSION_VERSION: 4.1.0-beta.3+rf20fd5e373
    defaults:
      run:
        working-directory: ${{ env.working-directory }}

    steps:
      - uses: actions/checkout@v5

      - name: Install buildah
        run: |
          sudo apt-get update
          sudo apt-get install -y buildah qemu-user-static

      - name: Build the transmission-daemon
        run: |
          chmod +x build_transmission-daemon.sh
          ./build_transmission-daemon.sh ${{ inputs.arch }}

      - name: Install b2sum
        run: |
          sudo apt-get update
          sudo apt-get install -y coreutils

      - name: Calculate b2sum
        run: |
          b2sum out/* > out/transmission-daemon-${{ env.TRANSMISSION_VERSION }}-${{ inputs.arch }}.b2sum

      - name: Make release transmission-daemon tarball
        run: |
          /bin/tar clJf transmission-daemon-${{ env.TRANSMISSION_VERSION }}-${{ inputs.arch }}.tar.xz out/*

      - name: Upload the transmission-daemon tarball
        uses: actions/upload-artifact@v4.6.2
        with:
          name: transmission-daemon-${{ env.TRANSMISSION_VERSION }}-${{ inputs.arch }}.tar.xz
          path: ${{ env.working-directory }}/transmission-daemon-${{ env.TRANSMISSION_VERSION }}-${{ inputs.arch }}.tar.xz
          retention-days: 1
